admin: 
  port: 9990

namers:
  - kind: io.l5d.consul
    prefix: /io.l5d.linker_to_consul
    host: docker.for.mac.localhost
    port: 8500
    includeTag: false
    useHealthCheck: true
    setHost: true
    consistencyMode: stale
    failFast: true
    preferServiceAddress: true

routers:
# OUT
# http 1.1: service -> linkerd -> [linkerd] -> service
# should lookup local service then filter down to local node
- label: /http-consul-in
  protocol: http
  servers:
    - port: 4141
      ip: 0.0.0.0
      # tls:
        # certPath: /etc/linkerd/server.crt
        # keyPath: /etc/linkerd/server.crt
  dtab: |
    /svc  => /#/io.l5d.linker_to_consul/.local;
  identifier:
    kind: io.l5d.header.token
  interpreter:
    kind: default
    transformers:
      - kind: io.l5d.localhost

# Don't send data to Buoyant
usage:
  orgId: linkerd-examples-consul
  enabled: false