version: '3'
services:
  microservice:
    # build: .
    image: alextanhongpin/web
    # Unable to scale up if we assign a name
    # container_name: node-microservice
    ports:
    - 8080
    # expose: Exposing ports is unnecessary - services on the same network can access each other's containers on any port.
    # expose:
    # - 8080
    depends_on:
    - database
    environment:
      MONGO_URI: mongodb://database:27017
  visualizer:
    image: dockersamples/visualizer
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    ports: 
    - 8080
  database:
    image: mongo:latest
    ports:
    - 27017
    # networks:
    #   mapp:
  client:
    # build: .
    image: alextanhongpin/web-client
    ports:
    - 8080
    links:
    - microservice
    depends_on:
    - microservice
    environment:
      SERVICE_URI: http://microservice

# networks:
#   mapp:
