version: '3'
services:
  consul:
    image: consul:0.9.0
    ports:
    - 8500:8500

  linkerd:
    image: buoyantio/linkerd:1.1.2
    command: /config.yaml
    volumes:
      - ./linkerd/linkerd.conf.yaml:/config.yaml
    ports:
      - 9990:9990
      - 4140:4140
      - 4141:4141
    depends_on:
    - registrator
  
  registrator:
    image: gliderlabs/registrator:v7
    command: -ip=docker.for.mac.localhost consul://consul:8500
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
    - consul

  server:
    image: alextanhongpin/echo
    ports:
    - 8080
    environment:
      - SERVICE_NAME=api
      - SERVICE_TAGS=svc
      - SERVICE_REGION=us2

  # Metrics
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
    - 9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    # command: -config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    # volumes:
    #  - grafana_data:/var/lib/grafana
    # environment:
    # - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
    - prometheus
    ports:
    - 3000

  node_exporter:
    image: prom/node-exporter:latest
    ports:
    - 9100

volumes:
  prometheus_data: {}
  grafana_data: {}