version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    # volumes:
    # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
    - esnet
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch1
    links:
    - elasticsearch1:elasticsearch
    # environment:
    # - SERVER_NAME=server.name
    # - KIBANA_DEFAULTAPPID=kibana.defaultAppId
    # - XPACK_MONITORING_ENABLED=xpack.monitoring.enabled
    # - ELASTICSEARCH_URL=http://elasticsearch1/9200
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    volumes:
    - ./tmp/es:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - esnet
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  #   environment:
  #   - cluster.name=docker-cluster
  #   - bootstrap.memory_lock=true
  #   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   - "discovery.zen.ping.unicast.hosts=elasticsearch1"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   # mem_limit: 1g
  #   volumes:
  #   - ./tmp/es:/usr/share/elasticsearch/data
  #   networks:
  #   - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    volumes:
    - ./tmp/logstash:/usr/share/logstash/pipeline
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
    - esnet
    ports:
     - 9500:9500
     - 9600:9600
     - 5000:5000
    depends_on:
    - elasticsearch1
    links:
    - elasticsearch1:elasticsearch
    environment:
    - HOSTNAME=elasticsearch
    # command: -e ./usr/share/logstash/pipeline/logstash.conf
  web:
    image: alextanhongpin/echo:0.0.3
    ports:
    - 8080:8080
  # nginx:
  #   image: nginx
    logging:
      driver: gelf
      options:
        gelf-address: udp://docker.for.mac.localhost:12201
        tag: fe
    networks:
    - esnet
  api:
    # will not work for go containers
    # build: .
    image: alextanhongpin/web-go
    expose:
    - 8080
    ports:
    - 8080
    # logging:
    #   driver: fluentd
      # options:
      #   fluentd-address: udp://docker.for.mac.localhost:12201
      #   tag: next
    logging:
      driver: syslog
      options:
        syslog-address: tcp://docker.for.mac.localhost:5000
        # syslog-facility: daemon
    depends_on:
    - logstash
    networks:
    - esnet

# volumes:
#   esdata1:
#     driver: local
#   esdata2:
#     driver: local

networks:
  esnet:
