version: '3'
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    # network_mode: host
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command: -config.file=/etc/prometheus/prometheus.yml

  client:
    image: alextanhongpin/go-prometheus-client:latest
    ports:
    - 8080:8080

  grafana:
    image: grafana/grafana
    # volumes:
    #  - grafana_data:/var/lib/grafana
    # environment:
    # - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
    - prometheus
    ports:
    - 3000:3000

  node_exporter:
    image: prom/node-exporter:latest
    ports:
    - 9100:9100

volumes:
  prometheus_data: {}
  grafana_data: {}